swagger: '2.0'
info:
  version: 1.1.3
  title: Netatmo
  description: |
    <h3>Welcome to the Netatmo swagger on-line documentation !</h3>
    This site is a complement to the official <a href="https://dev.netatmo.com/">Netatmo developper documentation</a> using swagger to bring interactivity and easy testing of requests with the "try it" button (authenticate with the authorization code OAuth2 flow by clicking the authenticate button in the methods). You can find the source code for this site can be found in the project <a href="https://github.com/cbornet/netatmo-swagger-ui">netatmo-swagger-ui</a>. You can also use the online <a hr[...]
  termsOfService: 'https://dev.netatmo.com/dev/resources/legal/introduction'
  license:
    name: 'Netatmo : Terms of Service'
    url: 'https://dev.netatmo.com/dev/resources/legal/introduction'
  contact:
    name: Netatmo
    email: contact-api@netatmo.com
host: api.netatmo.net
basePath: /api
schemes:
  - https
tags:
  - name: station
    description: Weather station specific methods
  - name: healthyhomecoach
    description: Healthy Home Coach specific methods
  - name: thermostat
    description: Thermostat specific methods
  - name: welcome
    description: Welcome specific methods
  - name: public
    description: Public stations specific methods
  - name: partner
    description: Partner API specific methods
  - name: deprecated
    description: These methods are no longer maintained nor supported
paths:
  /getpublicdata:
    get:
      tags:
        - public
      description: Retrieves publicly shared weather data from Outdoor Modules within a predefined area.
      operationId: getpublicdata
      security:
        - code_oauth: []
        - password_oauth: []
  /getuser:
    get:
      tags:
        - deprecated
      description: |
        The method getuser returns information about a user such as prefered language, prefered units, and list of devices.
      operationId: getuser
      deprecated: true
      security:
        - code_oauth: []
        - password_oauth: []
  /devicelist:
    get:
      tags:
        - deprecated
      description: |
        The method devicelist returns the list of devices owned by the user, and their modules.
        A device is identified by its _id (which is its mac address) and each device may have one, several or no modules, also identified by an _id.
      operationId: devicelist
      deprecated: true
      security:
        - code_oauth:
            - read_thermostat
            - read_station
        - password_oauth:
            - read_thermostat
            - read_station
  /getmeasure:
    get:
      tags:
        - station
        - thermostat
        - partner
        - public
      description: |
        The method getmeasure returns the measurements of a device or a module.
      operationId: getmeasure
      security:
        - code_oauth:
            - read_thermostat
            - read_station
        - password_oauth:
            - read_thermostat
            - read_station
  /getthermostatsdata:
    get:
      tags:
        - thermostat
      description: The method getthermostatsdata returns information about user's thermostats such as their last measurements.
      operationId: getthermostatsdata
      security:
        - code_oauth:
            - read_thermostat
        - password_oauth:
            - read_thermostat
  /getstationsdata:
    get:
      tags:
        - station
      description: The method getstationsdata Returns data from a user Weather Stations (measures and device specific data).
      operationId: getstationsdata
      security:
        - code_oauth:
            - read_station
        - password_oauth:
            - read_station
  /gethomecoachsdata:
    get:
      tags:
        - healthyhomecoach
      description: The method gethomecoachsdata Returns data from a user Healthy Home Coach Station (measures and device specific data).
      operationId: gethomecoachsdata
      security:
        - code_oauth:
            - read_homecoach
        - password_oauth:
            - read_homecoach
  /getthermstate:
    get:
      tags:
        - deprecated
      description: 'The method getthermstate returns the last Thermostat measurements, its current weekly schedule, and, if present, its current manual temperature setpoint.'
      operationId: getthermstate
      deprecated: true
      security:
        - code_oauth:
            - read_thermostat
        - password_oauth:
            - read_thermostat
  /syncschedule:
    post:
      tags:
        - thermostat
      description: The method syncschedule changes the Thermostat weekly schedule.
      operationId: syncschedule
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth:
            - write_thermostat
  /setthermpoint:
    post:
      tags:
        - thermostat
      description: The method setthermpoint changes the Thermostat manual temperature setpoint.
      operationId: setthermpoint
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth:
            - write_thermostat
  /switchschedule:
    post:
      tags:
        - thermostat
      description: The method switchschedule switches the Thermostat's schedule to another existing schedule.
      operationId: switchschedule
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth:
            - write_thermostat
  /createnewschedule:
    post:
      tags:
        - thermostat
      description: The method createnewschedule creates a new schedule stored in the backup list.
      operationId: createnewschedule
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth:
            - write_thermostat
  /partnerdevices:
    get:
      tags:
        - partner
      description: The method partnerdevices returns the list of device_id to which your partner application has access to.
      operationId: partnerdevices
      security:
        - code_oauth: []
        - password_oauth: []
  /gethomedata:
    get:
      tags:
        - welcome
      description: |
        Returns information about users homes and cameras.
      operationId: gethomedata
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth:
            - access_camera
            - read_camera
  /getcamerapicture:
    get:
      tags:
        - welcome
      description: |
        Returns the snapshot associated to an event.
      operationId: getcamerapicture
      security:
        - code_oauth: []
        - password_oauth: []
  /geteventsuntil:
    get:
      tags:
        - welcome
      description: |
        Returns the snapshot associated to an event.
      operationId: geteventsuntil
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth:
            - access_camera
            - read_camera
  /getlasteventof:
    get:
      tags:
        - welcome
      description: |
        Returns most recent events.
      operationId: getlasteventof
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth:
            - access_camera
            - read_camera
  /getnextevents:
    get:
      tags:
        - welcome
      description: |
        Returns previous events.
      operationId: getnextevents
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth:
            - access_camera
            - read_camera
  /setpersonsaway:
    post:
      tags:
        - welcome
      description: |
        Sets a person as 'Away' or the Home as 'Empty'. The event will be added to the user’s timeline.
      operationId: setpersonsaway
      security:
        - code_oauth:
            - write_camera
        - password_oauth:
            - write_camera
  /setpersonshome:
    post:
      tags:
        - welcome
      description: |
        Sets a person as 'At home'.
      operationId: setpersonshome
      security:
        - code_oauth:
            - write_camera
        - password_oauth:
            - write_camera
  /addwebhook:
    get:
      tags:
        - welcome
      description: |
        Links a callback url to a user.
      operationId: addwebhook
      security:
        - code_oauth: []
        - password_oauth: []
  /dropwebhook:
    get:
      tags:
        - welcome
      description: |
        Dissociates a webhook from a user.
      operationId: dropwebhook
      security:
        - code_oauth: []
        - password_oauth: []
securityDefinitions:
  code_oauth:
    type: oauth2
    authorizationUrl: 'https://api.netatmo.net/oauth2/authorize'
    tokenUrl: 'https://api.netatmo.net/oauth2/token'
    flow: accessCode
    scopes:
      read_station: Read weather station's data
      write_thermostat: Configure the thermostat
      read_thermostat: Read thermostat's data
      read_camera: Read welcome camera's data
      access_camera: Access welcome camera
      write_camera: Write welcome camera's data
      read_homecoach: Read data coming from Healthy Home Coach
  password_oauth:
    type: oauth2
    tokenUrl: 'https://api.netatmo.net/oauth2/token'
    flow: password
    scopes:
      read_station: Read weather station's data
      write_thermostat: Configure the thermostat
      read_thermostat: Read thermostat's data
      read_camera: Read welcome camera's data
      access_camera: Access welcome camera
      write_camera: Write welcome camera's data
      read_homecoach: Read data coming from Healthy Home Coach